import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/common/NavigationBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Centribal App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  console.log(params, "params");
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <ToastContainer />
        <NavigationBar></NavigationBar>
        {children}
      </body>
    </html>
  );
}
